apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgBuDUwdPCoUspq4OBpWigl4nN5gJ68SEPdQOWrogdgKAWWmsJIs1n5CxOxuX7KiSSjQpKIpiPIFibbGWRJrzS2JS2c186iKLdH31teGVNlDKU7OKUb/G9RDgEY2v1xFsZ/spBX7unOceVcdv6dR0EQqpO1Q5S1qE+LqxxLGOZ3c62CQJGT0vLzIfVteaPYSn1mtzJOkaANlRRURt9dXqxa0fXs61jySxCick7QJyyhxENQo3Q7QDyb+QGeBPVQrhy4oHFwbnEqc/ssgAwpKMP79hVuEbHBw1bUrA0dU0u15aByS6wuafcWdXA3BQiIdhFn/1Vb0a1ZYlNdPHXb85P2qf9wrRb+SXGyYOyyCBFBzf06p51QzPOl5w9g+nVWtWfzfese6Ty73F14lpCJQbrCYIB2JxIdugCbWeGmh1hJoZLD7+JDQpREJcgVrmpuuD82+OVqlB9GE5b4XOFfCc90xSgUignL005QS0t7yttBCjLKu0f/W9qSVhnYHTyzu/zaC7Rr4WsKYAF20wxwf4mPxcYGj02ZXN5E1FLCmm3QDnJWH36qlUbfuv0k58H8ek+sMDdOOScn0Ucy+teuFagOAVMb8pnFtHPIYVBMgMwL9tHpI+9kJ9ks97JObpzymffWYX4k2uFHbmAP2x2yfODz/l+MK+XY18BckQ7SqXJT5ueYTY7pBZKtrP6aUfnD+ka6dO+gQ4j3hKbwidBfsknUpEfv0ZKCpaMfZq4VMETh40rM0TPWI6vU=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque

